### ISSUE TITLE
Got errors while building

### ISSUE THREAD

**Issue by TraxXavier** [marytts/marytts-installer#14]
trax@kubuntu:~/Downloads/marytts-installer-5.2$ ./marytts install:cmu-slt
Downloading http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/trax/.gradle/wrapper/dists/gradle-2.14.1-bin/ev4hc1s4g1oc9yuae0b81rdza/gradle-2.14.1-bin.zip to /home/trax/.gradle/wrapper/dists/gradle-2.14.1-bin/ev4hc1s4g1oc9yuae0b81rdza
Set executable permissions for: /home/trax/.gradle/wrapper/dists/gradle-2.14.1-bin/ev4hc1s4g1oc9yuae0b81rdza/gradle-2.14.1/bin/gradle
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
:cmu-slt:payload

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':cmu-slt:marytts'.
> Could not resolve de.dfki.mary:voice-cmu-slt:5.2.
  Required by:
      MaryTTS:cmu-slt:5.2
   > Could not resolve de.dfki.mary:voice-cmu-slt:5.2.
      > Could not get resource 'https://jcenter.bintray.com/de/dfki/mary/voice-cmu-slt/5.2/voice-cmu-slt-5.2.pom'.
         > Could not GET 'https://jcenter.bintray.com/de/dfki/mary/voice-cmu-slt/5.2/voice-cmu-slt-5.2.pom'.
            > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.987 secs
trax@kubuntu:~/Downloads/marytts-installer-5.2$

**Comment by psibre** [comment]
At first I couldn't reproduce this, but then I tried with a clean `openjdk` docker container. At which point I got a *different* error.

**Comment by psibre** [comment]
Turns out a recent upgrade on mary.dfk.de had broken the path to the Ivy repo serving the required unitselection artifacts. I've symlinked it to restore functionality until we have a proper fix.
Should be working now.
