### ISSUE TITLE
How to install MaryTTS 5.2?

### ISSUE THREAD

**Issue by hoang408** [marytts/marytts-installer#6]
I try installing MaryTTS 5.2 following the steps on the Installer page.  The first command fails when executed inside the unpacked 5.2 folder:

marytts install:cmu-slt
--->marytts: command not found

Can someone please help?

**Comment by hoang408** [comment]
OK,
I follow the steps in this page: https://github.com/marytts/marytts/wiki/Local-MaryTTS-Server-Installation
And I got stuck in this step: 

sudo -u mary /local/mary/marytts/target/marytts-5.2/bin/marytts-server.sh
---> sudo: /local/mary/marytts/target/marytts-5.2/bin/marytts-server.sh: command not found

Please help.

**Comment by hoang408** [comment]
OK, so I use the 5.2 web installer and run ./marytts, it gets stuck at 

> Building 75% > :server

Quitting and re-run get stuck at:

> Building 0% > :server

Any help?

**Comment by psibre** [comment]
These are really two completely separate issues.
1. The [wiki page](https://github.com/marytts/marytts/wiki/Local-MaryTTS-Server-Installation) was outdated -- the script file name was renamed in marytts/marytts@3d84d8e27dd2b3946f80cf607e40c0251bebe231, so it would have worked if you had run the file actually present.
2. I cannot reproduce the issue with the web installer hanging. Running it on a vanilla system with OpenJDK 8 works just as expected (see [this log](https://github.com/marytts/marytts-installer/files/1512935/marytts.log)).
